# Generated by Django 3.2.8 on 2021-10-10 07:38

import json
from django.db import migrations

def create_data(apps, schema_editor):
    ColorSwatches = apps.get_model('color_swatches', 'ColorSwatches')

    colors_to_add = [
        {
            'name': 'RGB',
            'properties': {
                'red': {
                    'min':0,
                    'max': 255
                },
                'green':{
                    'min':0,
                    'max': 255
                },
                'blue':{
                    'min':0,
                    'max': 255
                }
            }
        },
        {
            'name': 'HSL',
            'properties': {
                'hue': {
                    'min':0,
                    'max': 360
                },
                'saturation':{
                    'min':0,
                    'max': 100
                },
                'lightness':{
                    'min':0,
                    'max': 100
                }
            }
        }
    ]

    for c in colors_to_add:
        ColorSwatches(
            name = c['name'],
            properties = json.dumps(c['properties'])
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('color_swatches', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
